[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"
